#!/usr/bin/env node
// =============================================================================
// Full project backup: schema + data + storage, in one timestamped folder.
//
//   npm run db:backup                 schema + all table data + storage files
//   npm run db:backup -- --no-storage skip downloading bucket objects
//   npm run db:backup -- --no-data    schema only (fast, tiny)
//
// Output: backups/<timestamp>/
//   schema.sql        self-contained DDL: types, tables, constraints, indexes,
//                     sequences, views, functions, triggers, RLS + policies,
//                     replica identity, realtime publication, grants, comments
//   data/<table>.json every row of every public table
//   storage/<bucket>/<path> downloaded bucket objects
//   manifest.json     row counts, FK edges, sequence ownership, bucket listing
//
// Restore with: npm run db:restore [backups/<timestamp>]
// Uses DATABASE_URL from the shell env or .env (same lookup as db-migrate).
// On a machine without global IPv6 the direct db host is unreachable: add
// `--pooler` to go through Supabase's IPv4 session pooler instead.
// =============================================================================
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { loadEnv, connect, stamp, apiFetch, repoRoot } from "./db-utils.mjs";

const env = loadEnv();

const noStorage = process.argv.includes("--no-storage");
const noData = process.argv.includes("--no-data");

const outDir = join(repoRoot, "backups", stamp());
const dataDir = join(outDir, "data");
const storageDir = join(outDir, "storage");
mkdirSync(outDir, { recursive: true });

const sql = await connect(env, { pooler: process.argv.includes("--pooler") });
const q = async (texts, ...args) => await sql(texts, ...args);
const esc = (s) => String(s).replaceAll("'", "''");

// ---------------------------------------------------------------------------
// 1. Schema introspection -> schema.sql
// ---------------------------------------------------------------------------
const parts = [];
parts.push(`-- Spaces1 database schema dump — ${new Date().toISOString()}
-- Generated by scripts/db-backup.mjs. Restore with scripts/db-restore.mjs.
set search_path to public, extensions; -- deparsed policy/function expressions and pgcrypto defaults may be unqualified
set check_function_bodies = off;     -- defer SQL function body parsing (pg_dump-style)
create schema if not exists public;
grant usage on schema public to anon, authenticated, service_role;
grant all on schema public to postgres;`);

// Extensions that live in the public schema (Supabase keeps most elsewhere).
const exts = await q`
  select e.extname, n.nspname from pg_extension e
  join pg_namespace n on n.oid = e.extnamespace where n.nspname = 'public'`;
for (const e of exts)
  parts.push(`create extension if not exists "${e.extname}" with schema public;`);

// Enum types
const enums = await q`
  select t.typname, string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder) labels
  from pg_type t join pg_enum e on e.enumtypid = t.oid
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public' group by t.typname order by t.typname`;
for (const e of enums) parts.push(`create type public.${e.typname} as enum (${e.labels});`);

// Tables + columns
const tables = await q`
  select c.relname, obj_description(c.oid) as comment
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('r', 'p')
  order by c.relname`;

const columnsByTable = {};
const tableDdl = [];
for (const t of tables) {
  const cols = await q`
    select a.attname,
           format_type(a.atttypid, a.atttypmod) as fulltype,
           pg_get_expr(d.adbin, d.adrelid) as defaultexpr,
           a.attnotnull,
           a.attidentity,
           a.attgenerated,
           col_description(a.attrelid, a.attnum) as comment
    from pg_attribute a
    left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
    where a.attrelid = to_regclass('public.' || ${t.relname}) and a.attnum > 0
      and not a.attisdropped
    order by a.attnum`;
  columnsByTable[t.relname] = cols.map((c) => c.attname);
  for (const c of cols)
    if (c.attgenerated === "s")
      tableDdl.push(
        `-- WARNING: public."${t.relname}"."${c.attname}" is a stored generated column; its expression is not dumped.`,
      );
  const lines = cols.map((c) => {
    let def = `  "${c.attname}" ${c.fulltype}`;
    if (c.attidentity === "a") def += " generated always as identity";
    else if (c.attidentity === "d") def += " generated by default as identity";
    else if (c.defaultexpr) def += ` default ${c.defaultexpr}`;
    if (c.attnotnull && !c.attidentity && c.attgenerated !== "s") def += " not null";
    return def;
  });
  tableDdl.push(
    `create table public."${t.relname}" (\n${lines.join(",\n")}\n);` +
      (t.comment ? `\ncomment on table public."${t.relname}" is '${esc(t.comment)}';` : ""),
  );
  for (const c of cols)
    if (c.comment)
      tableDdl.push(
        `comment on column public."${t.relname}"."${c.attname}" is '${esc(c.comment)}';`,
      );
}
const secTables = "-- ---------- tables ----------\n" + tableDdl.join("\n");

// Constraints (skip implicit ones; PK/unique/FK/check)
const cons = await q`
  select rel.relname as table, con.conname, pg_get_constraintdef(con.oid) as def
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace n on n.oid = con.connamespace
  where n.nspname = 'public' and con.contype in ('p', 'u', 'f', 'c')
  order by con.contype = 'f', rel.relname, con.conname`; // parents before FKs
const secCons =
  "-- ---------- constraints ----------\n" +
  cons
    .map((c) => `alter table public."${c.table}" add constraint "${c.conname}" ${c.def};`)
    .join("\n");

// Indexes (excluding those backing constraints)
const idx = await q`
  select rel.relname as table, pg_get_indexdef(i.indexrelid) as def
  from pg_index i
  join pg_class rel on rel.oid = i.indrelid
  join pg_namespace n on n.oid = rel.relnamespace
  where n.nspname = 'public'
    and not exists (select 1 from pg_constraint con where con.conname = i.indexrelid::regclass::text)
  order by rel.relname`;
const secIdx = "-- ---------- indexes ----------\n" + idx.map((i) => i.def + ";").join("\n");

// Sequences first (table defaults call nextval), then tables. Ownership
// alters come after the tables exist.
const seqs = await q`
  select s.schemaname, s.sequencename, s.data_type, s.start_value, s.last_value,
         d.relname as owned_table, d.attname as owned_column,
         exists (
           select 1 from pg_depend dep
           where dep.objid = format('public.%I', s.sequencename)::regclass and dep.deptype = 'i'
         ) as is_identity
  from pg_sequences s
  left join lateral (
    select t.relname, a.attname
    from pg_depend dep
    join pg_class t on t.oid = dep.refobjid and t.relkind = 'r'
    join pg_attribute a on a.attrelid = t.oid and a.attnum = dep.refobjsubid
    where dep.objid = format('public.%I', s.sequencename)::regclass and dep.deptype = 'a'
    limit 1
  ) d on true
  where s.schemaname = 'public' order by s.sequencename`;
const secSeqCreate =
  "-- ---------- sequences ----------\n" +
  seqs
    // Identity sequences are created implicitly by CREATE TABLE — pre-creating
    // them would collide.
    .filter((s) => !s.is_identity)
    .map(
      (s) =>
        `create sequence if not exists public."${s.sequencename}" start ${s.start_value ?? 1};`,
    )
    .join("\n");
const secSeqOwn = seqs
  .filter((s) => s.owned_table && !s.is_identity)
  .map(
    (s) =>
      `alter sequence public."${s.sequencename}" owned by public."${s.owned_table}"."${s.owned_column}";`,
  )
  .join("\n");

// Functions & procedures (skip aggregates/unsupported via try)
const fns = await q`
  select p.oid, p.proname from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind in ('f', 'p') order by p.proname, p.oid`;
const fnDefs = [];
for (const f of fns) {
  try {
    const rows = await sql.unsafe(`select pg_get_functiondef(${f.oid}) as def`);
    fnDefs.push(rows[0].def + ";");
  } catch {
    fnDefs.push(`-- skipped unparsable function oid ${f.oid} (${f.proname})`);
  }
}
const secFns = "-- ---------- functions ----------\n" + fnDefs.join("\n");

// Views
const views = await q`
  select c.relname, pg_get_viewdef(c.oid, true) as def, c.relkind
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('v', 'm') order by c.relname`;
const secViews =
  "-- ---------- views ----------\n" +
  views
    .map((v) =>
      v.relkind === "m"
        ? `create materialized view public."${v.relname}" as ${v.def};`
        : `create view public."${v.relname}" as ${v.def};`,
    )
    .join("\n");

// Assemble in dependency order: sequences -> tables -> ownership -> functions
// -> constraints -> indexes -> views (functions come early because views and
// constraints may call them; bodies are deferred by check_function_bodies).
parts.push(secSeqCreate, secTables, secSeqOwn, secFns, secCons, secIdx, secViews);

// Triggers
const trgs = await q`
  select tg.tgname, rel.relname as table, pg_get_triggerdef(tg.oid, true) as def
  from pg_trigger tg
  join pg_class rel on rel.oid = tg.tgrelid
  join pg_namespace n on n.oid = rel.relnamespace
  where n.nspname = 'public' and not tg.tgisinternal order by rel.relname, tg.tgname`;
parts.push("-- ---------- triggers ----------\n" + trgs.map((t) => t.def + ";").join("\n"));

// RLS enable/force + replica identity
const rls = await q`
  select c.relname, c.relrowsecurity, c.relforcerowsecurity, c.relreplident
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('r', 'p') order by c.relname`;
parts.push(
  "-- ---------- row level security ----------\n" +
    rls
      .map(
        (r) =>
          (r.relrowsecurity
            ? `alter table public."${r.relname}" enable row level security;\n`
            : "") +
          (r.relforcerowsecurity
            ? `alter table public."${r.relname}" force row level security;\n`
            : "") +
          (r.relreplident === "f"
            ? `alter table public."${r.relname}" replica identity full;\n`
            : ""),
      )
      .join(""),
);

// Policies
const pols = await q`
  select tablename, policyname, permissive, roles, cmd, qual, with_check
  from pg_policies where schemaname = 'public' order by tablename, policyname`;
parts.push(
  "-- ---------- policies ----------\n" +
    pols
      .map((p) => {
        const roles = (p.roles || []).filter((r) => r !== "public");
        return (
          `create policy "${esc(p.policyname)}" on public."${p.tablename}" as ${p.permissive} for ${p.cmd}` +
          (roles.length ? ` to ${roles.join(", ")}` : "") +
          (p.qual ? ` using (${p.qual})` : "") +
          (p.with_check ? ` with check (${p.with_check})` : "") +
          ";"
        );
      })
      .join("\n"),
);

// Realtime publication membership
const pubs = await q`
  select pubname, tablename from pg_publication_tables where schemaname = 'public' order by pubname, tablename`;
parts.push(
  "-- ---------- realtime publication ----------\n" +
    pubs
      .map(
        (p) =>
          `do $$ begin begin execute 'alter publication ${p.pubname} add table public."${p.tablename}"'; ` +
          `exception when duplicate_object then null; end; end $$;`,
      )
      .join("\n"),
);

// Grants (table + function acls beyond the owner defaults)
const grants = await q`
  select relkind, c.relname, pg_get_userbyid(a.grantee) as grantee,
         string_agg(distinct a.privilege_type, ',') as privs,
         a.is_grantable
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  cross join lateral aclexplode(c.relacl) a
  where n.nspname = 'public' and c.relkind in ('r', 'p', 'v', 'm', 'S', 'f')
    and pg_get_userbyid(a.grantor) <> pg_get_userbyid(a.grantee)
  group by relkind, c.relname, a.grantee, a.is_grantable order by c.relname`;
const kindOf = { r: "table", p: "table", v: "table", m: "table", S: "sequence", f: "table" };
parts.push(
  "-- ---------- grants ----------\n" +
    grants
      .map(
        (g) =>
          `grant ${g.privs} on ${kindOf[g.relkind] || "table"} public."${g.relname}" to ${g.grantee}` +
          `${g.is_grantable ? " with grant option" : ""};`,
      )
      .join("\n"),
);

writeFileSync(join(outDir, "schema.sql"), parts.join("\n\n") + "\n");
console.log(
  `schema.sql: ${tables.length} tables, ${fns.length} functions, ${pols.length} policies, ${trgs.length} triggers`,
);

// ---------------------------------------------------------------------------
// 2. Data — every row of every public table
// ---------------------------------------------------------------------------
const manifest = {
  created: new Date().toISOString(),
  tables: [],
  fks: [],
  sequences: seqs
    .filter((s) => !s.is_identity)
    .map((s) => ({
      name: s.sequencename,
      table: s.owned_table ?? null,
      column: s.owned_column ?? null,
      start: s.start_value ?? 1,
    })),
  buckets: [],
};

if (!noData) {
  mkdirSync(dataDir, { recursive: true });
  for (const t of tables) {
    const rows = await sql.unsafe(
      `select to_jsonb(x) as "row" from public."${t.relname.replace(/"/g, '""')}" x`,
    );
    const list = rows.map((r) => r.row);
    writeFileSync(join(dataDir, `${t.relname}.json`), JSON.stringify(list));
    manifest.tables.push({ name: t.relname, rows: list.length });
    process.stdout.write(`  ${t.relname}: ${list.length}\n`);
  }
  manifest.fks = cons
    .filter((c) => c.def.startsWith("FOREIGN KEY"))
    .map((c) => ({
      from: c.table,
      to: c.def.match(/REFERENCES (?:[\w"]+\.)?"?([\w]+)"?\s*\(/)?.[1],
    }))
    .filter((f) => f.to && f.from !== f.to);
} else {
  manifest.tables = tables.map((t) => ({ name: t.relname, rows: null }));
}

// ---------------------------------------------------------------------------
// 3. Storage — bucket list, object walk, downloads
// ---------------------------------------------------------------------------
try {
  const buckets = await apiFetch(env, "/storage/v1/bucket");
  for (const b of Array.isArray(buckets) ? buckets : []) {
    const entry = { name: b.name, public: !!b.public, objects: [], bytes: 0 };
    const stack = [""];
    while (stack.length) {
      const prefix = stack.pop();
      let offset = 0;
      for (;;) {
        const items = await apiFetch(env, `/storage/v1/object/list/${b.name}`, {
          method: "POST",
          body: JSON.stringify({
            prefix,
            limit: 500,
            offset,
            sortBy: { column: "name", order: "asc" },
          }),
        });
        if (!Array.isArray(items) || items.length === 0) break;
        for (const it of items) {
          const key = (prefix || "") + it.name;
          if (!it.id)
            stack.push(key + "/"); // folder -> recurse
          else entry.objects.push(key);
        }
        offset += items.length;
        if (items.length < 500) break;
      }
    }
    if (!noStorage && entry.objects.length) {
      mkdirSync(join(storageDir, b.name), { recursive: true });
      for (const key of entry.objects) {
        const buf = await apiFetch(env, `/storage/v1/object/authenticated/${b.name}/${key}`);
        const file = join(storageDir, b.name, ...key.split("/"));
        mkdirSync(join(file, ".."), { recursive: true });
        writeFileSync(file, buf);
        entry.bytes += buf.length;
      }
    }
    manifest.buckets.push(entry);
    console.log(
      `bucket ${b.name}: ${entry.objects.length} objects${noStorage ? " (listing only)" : `, ${Math.round(entry.bytes / 1024)} KiB`}`,
    );
  }
} catch (err) {
  console.warn(`storage skipped: ${String(err.message).slice(0, 160)}`);
}

writeFileSync(join(outDir, "manifest.json"), JSON.stringify(manifest, null, 2));

// Keep a rolling "current schema" for quick inspection / git tracking.
writeFileSync(
  join(repoRoot, "backups", "schema-current.sql"),
  readFileSync(join(outDir, "schema.sql"), "utf8"),
);

await sql.end();
console.log(`\nBackup complete: ${outDir.replace(repoRoot, ".")}`);
console.log("Restore with: npm run db:restore   (validates first; add --yes to apply)");
